openapi: 3.0.0
info:
  title: API Adoptions
  version: 1.0.0
  description: Endpoints para gestion de adopciones
tags:
  - Adoptions
paths:
  /api/adoptions:
    get:
      summary: Obtener todas las adopciones
      tags: [Adoptions]
      responses:
        "200":
          description: Lista de adopciones
        "401":
          description: No autorizado
  /api/adoptions/{uid}/{pid}:
    post:
      summary: Crear una adopcion
      tags: [Adoptions]
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Adopcion creada
        "400":
          description: ID invalido o mascota ya adoptada
        "404":
          description: Usuario o mascota no encontrada
        "403":
          description: Rol insuficiente
