openapi: 3.0.0
info:
  title: API Users
  version: 1.0.0
  description: Endpoints para gestion de usuarios
tags:
  - Users
paths:
  /api/users:
    get:
      summary: Listar todos los usuarios
      tags: [Users]
      responses:
        "200":
          description: Lista de usuarios
        "401":
          description: No autorizado
    post:
      summary: Crear un usuario
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Usuario creado
        "400":
          description: Email duplicado o error en los datos
  /api/users/{id}:
    get:
      summary: Obtener usuario por ID
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Usuario encontrado
        "404":
          description: Usuario no encontrado
    patch:
      summary: Actualizar usuario
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        "200":
          description: Usuario actualizado
        "400":
          description: Error en los datos
        "403":
          description: Rol insuficiente
    delete:
      summary: Eliminar usuario
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Usuario eliminado
        "404":
          description: Usuario no encontrado
        "403":
          description: Rol insuficiente
